### ISSUE TITLE
Custom sort context menu stops to work

### ISSUE THREAD

**Issue by arthniwa** [SebastianMC/obsidian-custom-sort#110]
Hi, I just found that the custom sort context menu no longer works. Clicking one of the options has no effect. Reordering existing bookmarks works fine.

As a remedy, I'm wondering how to manually edit those bookmarks, since adding bookmarks of files to the sortspec bookmark group produces different icons from those generated from adding them through the context menu.

I suspect this is caused by me adding a file to a sorted folder.

**Comment by SebastianMC** [comment]
Hi @arthniwa 

thanks for your report!

Could you please add some more details?
- platform: windows, macos, mobile, linux?
- version of Obsidian
- is the issue persistent after obsidian restart?
- what exactly is the observable effect?
  - context menu visible, clickable, yet nothing appears in the relevant bookmarks location?
  - do the menu actions work for other locations or they stopped working at all for all locations?
  - or are they creating a bookmark in incorrect location?
  - if the menu is visible, what options does it list for the item? I'm asking because the content of context menu is different for files/folder for which the plugin thinks that they are already present in bookmarks-for-sorting.
- what is the number of items in your bookmarks for sorting? If there are not too much, did you test removal of them and re-creation?
- as the last resort, did you try to examine the bookmarks.json file in your vault?
- I suspect that because of privacy aspects, it is not possible to show (a screenshot of) your bookmarks.

Regarding manual editing of the bookmarks-for-sorting: while manual creation of bookmarks groups (representing folders) is doable, manual creation of file bookmarks could be tricky, because the bookmarks-for-sorting intentionally include an anchor '#^-' (a link to a block '-' in the file). This is needed to let the bookmarks-for-sorting not interfere with real bookmarks.

While your goal is obviously to make it work on your side, my intentions is to fix the potential bug. Thank you in advance for any further input and clarifications to my questions!

**Comment by arthniwa** [comment]
Hi SebastianMC,

Thank you for the detailed reply and sorry about this. I found that it is due to my misreading. I read it as "Bookmark it+*children* for custom sorting" since I wanted to sort a folder, whereas in reality it's "siblings".
