### ISSUE TITLE
How to stop pushing newly created folders to the top before a child note is created?

### ISSUE THREAD

**Issue by raezyhsn** [SebastianMC/obsidian-custom-sort#111]
I just want the Obsidian file explorer to show the folders and its notes in the order they were created. (Like in onenote)

I have the following sortspec file:

```
---
sorting-spec: |
  target-folder: /*
  order-asc: advanced created
---
```

The problem is that when i create a new folder, it is pushed to the top until a note is created inside it.:

![image](https://github.com/SebastianMC/obsidian-custom-sort/assets/115896549/713ef00b-5030-458a-8ab3-aa495e0d1fb8)

I just want the folders and files to be shown in the order they are created. Nothing fancy.

**Comment by SebastianMC** [comment]
The immediate reason is that - in Obsidian - folders don't have the creation and modification date attributes. In other words, for a folder, technically you have no information when the folder was created or modified. As a result, they are not sortable with any date criteria. And there is no way to order the folders by creation or by modification date, unfortunately.

To overcome this limitation, one of early users of custom-sort plugin suggested to derive the folder creation and modification dates from their child-files. Yet this workaround is not applicable to empty folders (or folders containing only folder descendants).

Technically, such folders are on-the-fly (by the custom-sort plugin) stamped with _zero_ date, which logically maps to 1970 (as far as I remember) which - in turn - makes them the oldest items in the Vault :-)

In connection with ascending order by date (oldest-go-first), they are pushed to the top. Until you create a file inside such a folder, which moves them to the bottom, because of the creation date inheritance mechanism.

This is the explanation for the behavior which you observe.

And, as I think of this now, from the usability perspective, it could make sense to unconditionally push empty folders to the bottom, for date-based sorting rules, regardless whether the order is ascending or descending. This can be easily done.

Similar logic can be applied to sort by metadata (items w/o specific metadata to be pushed to the bottom, regardless if the sorting by metadata is ascending or descending). Same conclusion for sorting by bookmarks order - items not bookmarked pushed to the bottom.

I need to sleep with that improvement idea and then probably release a new version of the plugin containing the updated behavior.

Let me know what you think

**Comment by raezyhsn** [comment]
Thank you for taking the time to explain it in simple terms. Yeah, It would be cool to have this as a feature. Hoping to see it soon. Thanks : )

**Comment by SebastianMC** [comment]
Hi @raezyhsn 

plugin [release 2.1.0](https://github.com/SebastianMC/obsidian-custom-sort/releases/tag/2.1.0) contains this enhancement, check it out
