### ISSUE TITLE
Multi-folders instructions not works

### ISSUE THREAD

**Issue by arteny** [SebastianMC/obsidian-custom-sort#130]
Here is my sortspec file from root folder:
```
---
sorting-spec: |
    target-folder: /*
    %
    files
    attachments
	
    target-folder: /
    Все задачи
    Входящие
    Личное
    %
    Templates
    files
    sortspec
---

```
As result rules not works for any folder (attachments folder not the last) and also it is not correct working for root folder now, order is wrong. When it is written that all is successfully applied when turn on sort feature.

**Comment by colintedford** [comment]
Are you using the Catalyst build of Obsidian? It updated today and seems to be causing problems for Custom Sort. (Discussion in the \#insider-desktop-release channel on Discord.)

**Comment by arteny** [comment]
> Are you using the Catalyst build of Obsidian? It updated today and seems to be causing problems for Custom Sort. (Discussion in the #insider-desktop-release channel on Discord.)

no, I am using the regular version of Obsidian

**Comment by arteny** [comment]
@SebastianMC 

Tryied this, it is not working same way

**Comment by SebastianMC** [comment]
Hi @arteny,

I wanted to quickly reproduce your example locally and probably identified the issue.
I copied the sorting spec example to a new vault and it turned out there is a **tab character** in the empty line of the spec (the red highlight):

<img width="1024" alt="2024-02-08_18-32-32" src="https://github.com/SebastianMC/obsidian-custom-sort/assets/23032356/9d6ada56-8618-4b2b-8872-920007041c9c">

The **tab** character is not allowed in YAML syntax (which is used by Obsidian) and causes the entire metadata piece to be ignored by Obsidian parser.
To fix this either delete the tab character from the empty line or remove the empty line entirely.

BTW to help identifying such kind of errors, you can disable automatic integration with boomarks in the settings of custom-sort plugin:

<img width="917" alt="2024-02-08_18-39-29" src="https://github.com/SebastianMC/obsidian-custom-sort/assets/23032356/d25706bd-6d3f-4924-9796-bb9271e6b8bc">

If you do that, there will be no hidden automatic sorting specification and the plugin will complain that there is no sorting specification at all:

<img width="1018" alt="2024-02-08_18-40-20" src="https://github.com/SebastianMC/obsidian-custom-sort/assets/23032356/466a9847-d9f9-487b-b671-f6ff4f3ba195">

Please let me know if it helps

**Comment by arteny** [comment]
@SebastianMC removing tab from empty line fixed the issue, thanks
