### ISSUE TITLE
File list misbehave

### ISSUE THREAD

**Issue by EugeneShtoka** [SebastianMC/obsidian-custom-sort#139]
I was using custom sorting for quite some time, but recently it broke. I wasn't using an obsidian actively for couple of months, and when I got back to it, I saw that with custom order enabled, file explorer tab is misbehaving - it can show now files at all on obsidian start, it won't show added/deleted notes in subfolders, wouldn't represent notes drag&drop from  folder to folder, etc.
When I turn off the plugins, everythin is back to normal.
Custom sort plugin was one of the most useful plugins for me, as I'm using PARA metodology, and would like my folders in certain order, and in overall, it made so much order in my notes, not everything looks different...
I'm using arch linux, obsidian version 1.5.8, and plugin version 2.1.2

**Comment by SebastianMC** [comment]
Hi @EugeneShtoka

what you observe is a result of breaking changes introduced by Obsidian in a not-backward-compatible way, starting from 1.5.4

There is a series of tickets reported here for that problem, most representative #135 (recent) and #131 (an earlier one).

If you are only interested in getting back to order with your vault(s), then update the plugin first to current version (2.1.8) - the fix was included in 2.1.7. Then restart Obsidian and disable-(re)enable the plugin. It will work again correctly
