### ISSUE TITLE
When I “bookmark it”, documents/folders have strange suffixes after their names

### ISSUE THREAD

**Issue by hsingll** [SebastianMC/obsidian-custom-sort#155]
<img width="804" alt="Snipaste_2024-08-06_10-01-45" src="https://github.com/user-attachments/assets/c80b4af9-e2da-4891-815c-86c6d6ba63ac">
<img width="519" alt="Snipaste_2024-08-06_10-02-16" src="https://github.com/user-attachments/assets/52a0a8ca-f00d-4984-b967-53df6b18e1fa">

If you have anything else I can provide, please reply me.
I'm sorry I'm not a geek user and I don't know how to describe this problem more clearly.

**Comment by SebastianMC** [comment]
Hi @hsingll 

the _strange_ suffixes which you observe are intentional and they represent a bookmark of a section in a file, not the entire file.
They prevent the files bookmarked for sorting purposes from interfering with regular bookmarks of these files.

You can exercise the native bookmarking of Obsidian to see what I'm writing about: if you try to bookmark a section of a note (right click on a section title in note text) you will be able to bookmark that section and later on in bookmarks you will see similar suffix.

BTW such artificial suffix doesn't appear in bookmarked folders - if you bookmark a folder for sorting purposes, it is represented in bookmarks as a bookmarks-group, hence no need to involve artificial suffixes, because groups don't interfere with other groups or bookmarked folders.

**Comment by hsingll** [comment]
> Hi @hsingll
> 
> the _strange_ suffixes which you observe are intentional and they represent a bookmark of a section in a file, not the entire file. They prevent the files bookmarked for sorting purposes from interfering with regular bookmarks of these files.
> 
> You can exercise the native bookmarking of Obsidian to see what I'm writing about: if you try to bookmark a section of a note (right click on a section title in note text) you will be able to bookmark that section and later on in bookmarks you will see similar suffix.
> 
> BTW such artificial suffix doesn't appear in bookmarked folders - if you bookmark a folder for sorting purposes, it is represented in bookmarks as a bookmarks-group, hence no need to involve artificial suffixes, because groups don't interfere with other groups or bookmarked folders.

copy that, tnanks!
