### ISSUE TITLE
Plugin broken in obsidian 1.7.2

### ISSUE THREAD

**Issue by Azmoinal** [SebastianMC/obsidian-custom-sort#160]
Updating to the insider Obsidian 1.7.2 seems to broke the plugin.

My guess is that is related to a change into API done by Obsidian team
[more info here](https://docs.obsidian.md/Plugins/Guides/Understanding+deferred+views),

**Comment by SebastianMC** [comment]
Thanks a lot @Azmoinal for reporting this early!!!

After a quick check - indeed the problem is related to this new idea of deferred views.
There is also some other breaking change in Obsidian on top of that.

The Obsidian team is again contradicting their core idea - they declare that plugin's community is a fundamental part of Obsidian ecosystem, at the same time they don't care about backward compatibility and introduce breaking changes. This is like they did this for fifth time...

I wonder how many of existing plugins will break and will be left unmaintained after this revolution.

**Comment by Azmoinal** [comment]
Hi @SebastianMC, thanks a lot for the quick response and clarification.

Unfortunately, I'm not a developer so I cannot help you. 

I could report the situation to the discord insider channel, trying to push them to provide a possible solution.

I'm sad about the situation because your plugin is one of the most useful for me and it changes the way I use obsidian.

**Comment by SebastianMC** [comment]
Hi @Azmoinal 

a potential plugin-integration-point at technical level remains the function `getSortedFolderItems` - it is still exposed in 1.7.2
This will be the first investigation point, a next step.
At the same time I'm currently short on time which I could spend on the plugin (investigations, discussions, etc.)
I hope the official public release 1.7.x won't appear soon.

**Comment by SebastianMC** [comment]
The [2.1.14](https://github.com/SebastianMC/obsidian-custom-sort/releases/tag/2.1.14) version of the plugin (released a minute ago) works correctly with Obsidian 1.7.2

The long story short:
- the plugin has already been prepared for the specific Obsidian breaking changes
- the heavy lifting of investigation of new plugin-integration-point in Obsidian and updating the plugin code accordingly was done for Obsidian 1.6.0 and has been present in the plugin [2.1.9](https://github.com/SebastianMC/obsidian-custom-sort/releases/tag/2.1.9), released and in use since May this year. My memory wasn't kind enough to tell me that right away today ;-)
- the only remaining fix (applied today) was to make the plugin-integration-point detection logic smarter: not to verify the presence of the old integration point when actually the new integration point is going to be used
- I created a clone of the plugin repo (https://github.com/SebastianMC/obsidian-custom-sort-poc-obsitian-1-7-2) only to quickly find out that the code needed for Obsidian 1.7.2 is already there and the fix for today is an easy low-hanging-fruit
- I thanked myself for the heavy-lifting work done in May to make the plugin compatible with Obsidian 1.6.0+ :-)

Please update the plugin to [2.1.14](https://github.com/SebastianMC/obsidian-custom-sort/releases/tag/2.1.14), retest and let me know in case of problems

**Comment by bray** [comment]
Thanks for the quick fix! It seems to be working now when manually sorting via the toggling command. But it no longer automatically sorts when I first open Obsidian (desktop and mobile v1.7.2). I'm almost positive it did that automatically before... ?

**Comment by Azmoinal** [comment]
Hi @SebastianMC, I cannot test it right now on my desktop but on the iPad al start the plugin is enabled but at start the custom sorting is not applied (the orange icon is showed into the sidebar) activating it, all works fine.

**Comment by SebastianMC** [comment]
Hi @bray,
the behavior which you describe was first observed in Obsidian 1.6.3, reported under #147 with a fix released in June in [2.1.11](https://github.com/SebastianMC/obsidian-custom-sort/releases/tag/2.1.11). The fix only partially addressed the issue. It is possible that in Obsidian 1.7.3, because of their new 'lazy views' performance optimisation , the issue is more prevalent, observable more frequently.
If it is reproducible on demand please open a ticket.

Hi @Azmoinal,
it is possible that what you encounter is exactly the same as described by @bray 

Having fixed the blocker under this ticket, the less critical issue(s) can be reported and wait for convenient time.

Thanks for testing and providing the feedback!

**Comment by Azmoinal** [comment]
> Hi @bray,
> 
> the behavior which you describe was first observed in Obsidian 1.6.3, reported under #147 with a fix released in June in [2.1.11](https://github.com/SebastianMC/obsidian-custom-sort/releases/tag/2.1.11). The fix only partially addressed the issue. It is possible that in Obsidian 1.7.3, because of their new 'lazy views' performance optimisation , the issue is more prevalent, observable more frequently.
> 
> If it is reproducible on demand please open a ticket.
> 
> 
> 
> Hi @Azmoinal,
> 
> it is possible that what you encounter is exactly the same as described by @bray 
> 
> 
> 
> Having fixed the blocker under this ticket, the less critical issue(s) can be reported and wait for convenient time.
> 
> 
> 
> Thanks for testing and providing the feedback!

Hi,

Yes. It is the same issue. I didn't realized that @bray posted in the meantime I was writing. 

I can reproduce it on my iPad Pro M1 simply force quitting e reopening Obsidian. I would check on desktop before raising a new, specific,ticket of the remaining issue.

Thanks a lot for the quick fix.

**Comment by bray** [comment]
Hi @SebastianMC - I created https://github.com/SebastianMC/obsidian-custom-sort/issues/163. Thanks!
