### ISSUE TITLE
sortspec.md file doesn't works.

### ISSUE THREAD

**Issue by 22sh22** [SebastianMC/obsidian-custom-sort#181]
obsidian version is latest, 1.7.7 

Tested solution:---
1. disabled all other plugins except for this one.
2. deleted and reinstalled the plugin
3. disabled options about bookmark.
4. removed korean folders in sortspec
==============

i made sortspec file in root folder,
no more sortspec.md
![image](https://github.com/user-attachments/assets/c187d546-ff8d-4ffc-81b8-de6026839485)

belows are the content of sortspec
```
---
sorting-specs: |
	target-folder: /
	Daily Notes
	수집
	프로젝트
	영역
	자원
	보관
	Templates
	sortspec

	target-folder: Daily Notes/*
	< a-z
---
```

would find the problem?

**Comment by SebastianMC** [comment]
Hi @22sh22 

at glance, the first thing to ensure is that the sorting specification from your example exists in the note with title `sortspec` which means technically in the file named `sortspec.md`.

In other words, at the level of filesystem (e.g. finder on mac or file explorer in windows) you should see the file `sortspec.md` in the root folder. Then, at the level of Obsidian you will see simply `sortspec` entry.

The second thing to check is to use space characters instead of tabs characters for indentation.
In the example which you posted I see tab characters - please replace them with spaces (e.g. two consecutive spaces, for readability).

Tab characters are not allowed by Obsidian in the YAML (aka note properties) section.

**Comment by 22sh22** [comment]
Thank you for your help!
Unfortunately, It didn't work.
it's file name have been "sortspec.md"(in obsidian "sortspec"),
and I tried changing tabs to "  ".
![image](https://github.com/user-attachments/assets/191815ec-57eb-4434-8318-ecea59d86be1)
![image](https://github.com/user-attachments/assets/82bd2aae-ab8e-407f-b864-5e680b8277c7)

**Comment by SebastianMC** [comment]
HI @22sh22 

please create an empty vault from scratch. Inside of it create two or three test folders and same number of test files. They could resemble your real vault. Then create the sortspec node (underlying file: sortspec.md), put some basic sorting specification there and see if it works. If it doesn't work please zip the test vault and send to me (attach to a comment here). My time is limited now and the information in your report so far are not sufficient to diagnose the source of the problem.

**Comment by 22sh22** [comment]
@SebastianMC 
2 files: my real vault and test vault

in my vault: after trying using bookmark sort -> removed all bookmarks but always shows "succeeded" and nothing changes (even after I disabled all bookmark sort options)

test Vault:  "parsing failed" even there is sortspec.md

Thank you for reading this..

https://drive.google.com/file/d/1C3Xh1WPMQUsJaA5HgD-Np-TeUWDMK43H/view?usp=sharing

https://drive.google.com/file/d/1CGFNsZ_uw2Af3xGJ6LY6zQ3tQWBQqPmW/view?usp=sharing

**Comment by SebastianMC** [comment]
Hi @22sh22 

downloaded the test vault and opened `sortspec.md` in text editor.
The first thing to fix is the name of the property: it should be `sorting-spec:` instead of `sorting-specs:`
Please correct this typo. Other than that the `sortspec.md` looks fine.

**Comment by 22sh22** [comment]
@SebastianMC 
Oh... It works well.
Sorry for my foolish mistake.
Thanks for your help!!
