### ISSUE TITLE
Does this plugin allow moving items around in any order?

### ISSUE THREAD

**Issue by YousufSSyed** [SebastianMC/obsidian-custom-sort#51]

**Comment by SebastianMC** [comment]
Hi @YousufSSyed

the quick answer is: yes, this plugin allows placing the items in any desired order.

At the same time if you ask about _moving items_ in the sense of _drag & drop_ feature, it is not supported. This plugin works off a textual specification of how the items should be ordered. There was a plugin _obsidian-bartender_ which supported drag & drop functionality in File Explorer. I don't have information if it is up-to-date and still maintained

Back to this plugin: using the simple textual specification you can place the items in any desired order. Some examples:
- list (in the config) the items by name in the desired order (this is the simplest case and equivalent of manual ordering)
- list only some of items, these which should be pinned to the top and/or to the bottom, and let the other (not listed) items be placed automatically below, above or between
- instead of listing full names you can list name prefixes, or suffixes. Or metadata key
- you can distinguish between files and folders or treat them equally
- you can sort by the _starred_ / _unstarred_ items and - for example - pin starred items to the top
- you can involve automatic sorting rules, by name, by numerical part of the name (prefix or suffix or infix), by dates, by metadata
- other options supported

**Comment by YousufSSyed** [comment]
Good answer.
