### ISSUE TITLE
Possible Bug: Incorrect Chinese Support

### ISSUE THREAD

**Issue by xsinbh** [SebastianMC/obsidian-custom-sort#93]
## Problem
This is the sorting-spec:
```
  target-folder: /
  学业笔记
  Daliy
  编译原理
  数据库
  其他
```

This is the effect:
![image](https://github.com/SebastianMC/obsidian-custom-sort/assets/112634985/4c9da4b9-112d-426d-9f96-a9f8a9e336ff)

Obviously the sorting didn't fit my expectation.
The right order should be
```
学业笔记
Daily
编译原理
数据库
其他
任务管理器
Callouts
sortspec
Template - Daily Task
Template - New Task
```

This sorting-spec is just the same case as simple-case 2 in the document.
I hope my perception to the grammar was correct.

If you can't type Chinese, you can copy the Chinese above for tests.

Looking forward to your reply!

## Appendix
This is the default a-z sorting in Obsidian
![image](https://github.com/SebastianMC/obsidian-custom-sort/assets/112634985/32ebaa2c-dc17-4b1d-bf17-c33194f5fd72)

**Comment by SebastianMC** [comment]
Hi @xsinbh 

I did a visual comparison of the screenshots (thank you for them! They really bring clarity):

![Obsidian custom sort 93](https://github.com/SebastianMC/obsidian-custom-sort/assets/23032356/f9b12d9c-4850-41dc-98fe-3a453b271f30)

I see the Chinese notes are ordered correctly, as set in the `sorting-spec`.
Then, the 'Daily' note is ignored because of a typo in the spec (`Daliy`) and in result it falls into the group of items to be sorted alphabetically below. In other words, if a `sorting-spec:` contains entries which don't match any note, these entries simply have no effect. 

Is the misplaced 'Daily' note the only item not sorted correctly in your report?

**Comment by xsinbh** [comment]
Oh, I see...
I really typed `daliy` 😆 
My fault, sorry for the interruption...
Thanks!
